### ISSUE TITLE
Research task: SPIFFS attached to GATT service "arduino way"

### ISSUE THREAD

**Issue by faddat** [universelabs/universe-mobile#11]
**Description**
Research GATT-attached storage on the ESP32, arduino style

**Comment by faddat** [comment]
https://randomnerdtutorials.com/install-esp32-filesystem-uploader-arduino-ide/


THIS IS GOOD!

**Comment by guylepage3** [comment]
Pushing this to [Sprint 7](https://github.com/orgs/universelabs/projects/8).

**Comment by faddat** [comment]
feather related; closing
