### ISSUE TITLE
Add Feather iPhone support

### ISSUE THREAD

**Issue by faddat** [universelabs/universe-mobile#13]
**Description**
Add iPhone support for enclave.

**Comment by guylepage3** [comment]
Hey @faddat can you provide a description for this? Thanks.

**Comment by guylepage3** [comment]
@faddat what is this issue? I don't understand it as it's just the issue template. Can we close this out?

**Comment by faddat** [comment]
Feather was working on android, not iphone.  Closing this issue now.
