### ISSUE TITLE
Bluetooth Security Vulnerability

### ISSUE THREAD

**Issue by faddat** [universelabs/universe-mobile#15]
**Description**
The Knob attack effects bluetooth devices and may cause privilege escalation risks on host devices.  

https://knobattack.com/

We should ensure that our devices are not effected by this attack vector.

**Comment by itamarreif** [comment]
Verge article says this only applies to regular BT, not BLE:

https://www.theverge.com/2019/8/16/20808597/bluetooth-device-flaw-hackers-vulnerability-data-encryption-cybersecurity-knob

**Comment by itamarreif** [comment]
Usenix paper with more info 

https://www.usenix.org/system/files/sec19-antonioli.pdf

**Comment by faddat** [comment]
No Bluetooth + keys.
