### ISSUE TITLE
Create GATT service exposing a characteristic

### ISSUE THREAD

**Issue by faddat** [universelabs/universe-mobile#6]
We need to create a GATT service that exposes a characteristic.  For testing, we agreed on a "getkey" characteristic that returns "universe".  

This replaces #4

**Comment by faddat** [comment]
Today / Tomorrow I am going to try to get a grip on this:

https://github.com/espressif/esp-idf/blob/6fe853a2c/examples/bluetooth/bluedroid/ble/gatt_server_service_table/tutorial/Gatt_Server_Service_Table_Example_Walkthrough.md

**Comment by guylepage3** [comment]
Pushing this to [Sprint 7](https://github.com/orgs/universelabs/projects/8).

**Comment by faddat** [comment]
feather related; closing
