### ISSUE TITLE
Understand the difference between Arduino-style ESP32 and Espressif IDF Style ESP32

### ISSUE THREAD

**Issue by faddat** [universelabs/universe-mobile#7]
I loved the simple code and user experience when using Arduino.  

But the IDF stuff may be different.

So now, the task is to understand the difference between using Arduino for ESP32 development and using the IDF libraries and such.  Some of the Arduino stuff says that it is sourced in the IDF.  

I also haven't truly figured out *what* is going on with code style in Arduino.  

Love the UX in Arduino, but there's something that I'm not getting here.

**Comment by guylepage3** [comment]
@faddat I'm pushing this to [Sprint 7](https://github.com/orgs/universelabs/projects/8).

**Comment by guylepage3** [comment]
Closing this issue
